name: Automatically format the code with ruff
on:
  - push

jobs:
  ruff-format:
    permissions:
      contents: write
      pull-requests: write
    name: Format the code with ruff and push the changes
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') && !(startsWith(github.ref, 'refs/heads/') && endsWith(github.ref, '.x')) && !startsWith(github.ref, 'refs/heads/release')
    env:
      GIT_COMMIT_MESSAGE: |
        Format with ruff

        See https://icalendar.readthedocs.io/en/stable/contribute/development.html#code-format
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . --group formatting
      - name: Format the code with ruff
        run: ruff format
      - name: Format the code with ruff check
        run: ruff check --fix
      - name: Show the changes
        run: |
          git status
          git diff
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "${GIT_COMMIT_MESSAGE}" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
